import { useEffect, useMemo, useState } from 'react';
import { currentUser, deleteRow, getStats, getTableData, saveRow, signIn, signOut, subscribeToAuth } from './services/data';
import { TABLES, formatDate, isSpecialTable } from './config';

const emptyForm = { nama: '', nama_usaha: '', alamat: '', no_telefon: '', email: '', izin: '', link_gdrive: '', tanggal_terbit: '', masa_berlaku: '' };

function Toast({ items }) { return <div className="toast-stack">{items.map(item => <div className={`toast ${item.type}`} key={item.id}>{item.message}</div>)}</div>; }

function Login({ onLogin, notify }) {
  const [form, setForm] = useState({ username: '', password: '' });
  const [busy, setBusy] = useState(false);
  const submit = async (event) => {
    event.preventDefault();
    if (!form.username || !form.password) return notify('Username dan password wajib diisi.', 'error');
    setBusy(true); const result = await signIn(form.username, form.password); setBusy(false);
    if (result.success) onLogin(result.user); else notify(result.message || 'Login gagal.', 'error');
  };
  return <main className="login-screen"><form className="login-card" onSubmit={submit}>
    <div className="brand-mark">JABALEGA</div><p className="eyebrow">Panel Admin · Jasa Bantuan Legalitas</p>
    <h1>Selamat datang kembali</h1><p className="muted">Masuk untuk mengelola data client dan layanan.</p>
    <label>Email admin<input type="email" autoFocus value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} placeholder="admin@example.com" /></label>
    <label>Password<input type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="Masukkan password" /></label>
    <button className="button primary full" disabled={busy}>{busy ? 'Memproses...' : 'Masuk ke Dashboard'}</button>
  </form></main>;
}

function Sidebar({ page, setPage, user, onLogout }) { return <aside className="sidebar">
  <div className="sidebar-brand"><div className="brand-mark small">JABALEGA</div><span>Admin workspace</span></div>
  <div className="nav-caption">Ringkasan</div><button className={`nav-link ${page === 'dashboard' ? 'active' : ''}`} onClick={() => setPage('dashboard')}><span>▦</span> Dashboard</button>
  <div className="nav-caption">Data client</div>{Object.entries(TABLES).map(([key, config]) => <button key={key} className={`nav-link ${page === key ? 'active' : ''}`} onClick={() => setPage(key)}><span className="nav-dot" style={{ background: config.color }} />{config.label}</button>)}
  <div className="sidebar-user"><div className="avatar">{(user || 'A').slice(0, 1).toUpperCase()}</div><div><strong>{user || 'Admin'}</strong><small>Administrator</small></div><button className="logout" onClick={onLogout} title="Keluar">↪</button></div>
</aside>; }

function Dashboard({ stats, onSelect }) {
  const counts = stats?.table_counts || {};
  const max = Math.max(...Object.keys(TABLES).map(key => counts[key] || 0), 1);
  return <section className="page-content"><div className="page-intro"><div><p className="eyebrow">Overview</p><h1>Dashboard</h1><p className="muted">Pantau seluruh layanan legalitas dalam satu tempat.</p></div><div className="date-chip">{new Date().toLocaleDateString('id-ID', { dateStyle: 'long' })}</div></div>
    <div className="stat-grid"><button className="stat-card total" onClick={() => {}}><strong>{stats?.total ?? '—'}</strong><span>Total semua client</span></button>{Object.entries(TABLES).map(([key, config]) => <button className="stat-card" key={key} onClick={() => onSelect(key)}><strong>{counts[key] ?? '—'}</strong><span>{config.label}</span></button>)}</div>
    <div className="content-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">Distribusi</p><h2>Client per layanan</h2></div></div><div className="bars">{Object.entries(TABLES).map(([key, config]) => <div className="bar-row" key={key}><span>{config.label}</span><div className="bar-track"><i style={{ width: `${((counts[key] || 0) / max) * 100}%`, background: config.color }} /></div><b>{counts[key] || 0}</b></div>)}</div></div><Recent /></div>
  </section>;
}

function Recent() { const [rows, setRows] = useState([]); useEffect(() => { (async () => { const result = []; for (const table of Object.keys(TABLES)) { const response = await getTableData(table, 1); if (response.success) response.data.slice(0, 2).forEach(row => result.push({ ...row, table })); } setRows(result.slice(0, 8)); })(); }, []); return <div className="panel"><div className="panel-heading"><div><p className="eyebrow">Aktivitas</p><h2>Client terbaru</h2></div></div><div className="recent-list">{rows.length ? rows.map(row => <div className="recent-item" key={`${row.table}-${row.id}`}><div className="avatar muted-avatar">{row.nama?.slice(0, 1)}</div><div><strong>{row.nama}</strong><span>{row.nama_usaha || 'Nama usaha belum diisi'}</span></div><em>{TABLES[row.table].label}</em></div>) : <p className="empty">Belum ada data client.</p>}</div></div>; }

function DataPage({ table, notify, onChanged }) {
  const [data, setData] = useState({ rows: [], total: 0, page: 1, total_pages: 1 }); const [search, setSearch] = useState(''); const [modal, setModal] = useState(null); const [confirm, setConfirm] = useState(null); const [loading, setLoading] = useState(true);
  const load = async (page = data.page) => { setLoading(true); const result = await getTableData(table, page, search); if (result.success) setData({ rows: result.data, total: result.total, page: result.page, total_pages: result.total_pages }); else notify(result.message || 'Data gagal dimuat.', 'error'); setLoading(false); };
  useEffect(() => { load(1); }, [table, search]);
  const save = async (form, id) => { const result = await saveRow(table, form, id); if (result.success) { notify(result.message, 'success'); setModal(null); load(); onChanged(); } else notify(result.message || 'Gagal menyimpan data.', 'error'); };
  const remove = async () => { const result = await deleteRow(table, confirm.id); if (result.success) { notify(result.message, 'success'); setConfirm(null); load(); onChanged(); } else notify(result.message || 'Gagal menghapus data.', 'error'); };
  return <section className="page-content"><div className="page-intro compact"><div><p className="eyebrow">Data client</p><h1>{TABLES[table].label}</h1><p className="muted">Kelola informasi, dokumen, dan masa berlaku layanan.</p></div><button className="button primary" onClick={() => setModal({})}>＋ Tambah client</button></div>
    <div className="toolbar"><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Cari nama, usaha, atau telepon..." /><span>{data.total} data ditemukan</span></div><div className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>#</th><th>Client</th><th>Usaha</th>{isSpecialTable(table) ? <><th>Jenis izin</th><th>Telepon</th><th>Email</th></> : <><th>Alamat</th><th>Telepon</th><th>Tgl terbit</th><th>Masa berlaku</th><th>Dokumen</th></>}<th>Aksi</th></tr></thead><tbody>{loading ? <tr><td colSpan="10" className="empty">Memuat data...</td></tr> : data.rows.length ? data.rows.map((row, index) => <Row key={row.id} row={row} table={table} index={(data.page - 1) * 15 + index} onEdit={() => setModal(row)} onDelete={() => setConfirm(row)} />) : <tr><td colSpan="10" className="empty">Tidak ada data ditemukan.</td></tr>}</tbody></table></div><div className="pagination"><span>Halaman {data.page} dari {data.total_pages}</span><div><button disabled={data.page <= 1} onClick={() => load(data.page - 1)}>←</button><button disabled={data.page >= data.total_pages} onClick={() => load(data.page + 1)}>→</button></div></div></div>
    {modal && <ClientModal table={table} initial={modal} onClose={() => setModal(null)} onSave={save} />}{confirm && <Confirm name={confirm.nama} onClose={() => setConfirm(null)} onConfirm={remove} />}</section>;
}

function Row({ row, table, index, onEdit, onDelete }) { return <tr><td className="number">{index + 1}</td><td><strong>{row.nama}</strong></td><td>{row.nama_usaha || '-'}</td>{isSpecialTable(table) ? <><td>{row.izin || '-'}</td><td>{row.no_telefon || '-'}</td><td>{row.email || '-'}</td></> : <><td>{row.alamat || '-'}</td><td>{row.no_telefon || '-'}</td><td>{formatDate(row.tanggal_terbit)}</td><td>{formatDate(row.masa_berlaku)}</td><td>{row.link_gdrive ? <a href={row.link_gdrive} target="_blank" rel="noreferrer">Buka ↗</a> : '-'}</td></>}<td><div className="row-actions"><button onClick={onEdit} title="Edit">✎</button><button onClick={onDelete} title="Hapus">×</button></div></td></tr>; }

function ClientModal({ table, initial, onClose, onSave }) { const [form, setForm] = useState({ ...emptyForm, ...initial }); const special = isSpecialTable(table); const change = (key, value) => setForm({ ...form, [key]: value }); const submit = e => { e.preventDefault(); if (!form.nama) return; onSave(form, initial.id); }; return <div className="overlay"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow">{initial.id ? 'Perbarui data' : 'Data baru'}</p><h2>{initial.id ? 'Edit client' : 'Tambah client'}</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div><div className="form-grid"><Field label="Nama client *" value={form.nama} onChange={v => change('nama', v)} /><Field label="Nama usaha" value={form.nama_usaha} onChange={v => change('nama_usaha', v)} />{special ? <><Field label="Jenis izin *" value={form.izin} onChange={v => change('izin', v)} /><Field label="Email *" type="email" value={form.email} onChange={v => change('email', v)} /><Field label="No. telepon" value={form.no_telefon} onChange={v => change('no_telefon', v)} /></> : <Field label="No. telepon" value={form.no_telefon} onChange={v => change('no_telefon', v)} />}{!special && <label className="wide">Alamat<textarea value={form.alamat || ''} onChange={e => change('alamat', e.target.value)} /></label>}<Field label="Tanggal terbit" type="date" value={form.tanggal_terbit || ''} onChange={v => change('tanggal_terbit', v)} /><Field label="Masa berlaku" type="date" value={form.masa_berlaku || ''} onChange={v => change('masa_berlaku', v)} /><Field label="Link Google Drive" type="url" value={form.link_gdrive || ''} onChange={v => change('link_gdrive', v)} /></div><div className="modal-foot"><button type="button" className="button" onClick={onClose}>Batal</button><button className="button primary">{initial.id ? 'Perbarui' : 'Simpan'}</button></div></form></div>; }
function Field({ label, value, onChange, type = 'text' }) { return <label>{label}<input type={type} value={value || ''} onChange={e => onChange(e.target.value)} /></label>; }
function Confirm({ name, onClose, onConfirm }) { return <div className="overlay"><div className="confirm modal"><div className="warning">!</div><h2>Hapus data client?</h2><p>Data <strong>{name}</strong> akan dihapus permanen.</p><div className="modal-foot"><button className="button" onClick={onClose}>Batal</button><button className="button danger" onClick={onConfirm}>Ya, hapus</button></div></div></div>; }

export default function App() { const [user, setUser] = useState(null); const [page, setPage] = useState('dashboard'); const [stats, setStats] = useState(null); const [toasts, setToasts] = useState([]); const notify = (message, type = 'info') => { const id = Date.now(); setToasts(items => [...items, { id, message, type }]); setTimeout(() => setToasts(items => items.filter(item => item.id !== id)), 3500); }; const loadStats = async () => { const result = await getStats(Object.keys(TABLES)); if (result.success) setStats(result); }; useEffect(() => { currentUser().then(result => { if (result.success) setUser(result.user); }); subscribeToAuth(setUser); }, []); useEffect(() => { if (user) loadStats(); }, [user]); const login = account => { setUser(account); notify(`Selamat datang, ${account.email}.`, 'success'); }; const logout = async () => { await signOut(); setUser(null); setPage('dashboard'); }; if (!user) return <><Login onLogin={login} notify={notify} /><Toast items={toasts} /></>; return <><div className="app-shell"><Sidebar page={page} setPage={setPage} user={user.email} onLogout={logout} /><main className="main-content"><header className="topbar"><span className="mobile-brand">JABALEGA</span><span className="topbar-context">Workspace / {page === 'dashboard' ? 'Dashboard' : TABLES[page].label}</span><span className="online"><i /> Terhubung</span></header>{page === 'dashboard' ? <Dashboard stats={stats} onSelect={setPage} /> : <DataPage table={page} notify={notify} onChanged={loadStats} />}</main></div><Toast items={toasts} /></>; }
